### PR TITLE
DOC 40

### PR DESCRIPTION
**Pull request by StarfallProjects**
Note: due to JIRA project migration shenanigans, this is actually the PR for this story:
https://stoplightio.atlassian.net/browse/DOC-40

### CODE REVIEW

**Review by brianmrock — CHANGES_REQUESTED** [review]
On teh installation_guide.md, can we please put in a section to validate the installation was successful?  Maybe just a few steps to teach them how to troubleshoot that the installation is up and running. 

Also, would it make sense to include a FAQ?

**Comment by StarfallProjects** [comment]
@collinbachi can you help out with info on how to test the installation?

@brianmrock what did you have in mind for the FAQ? I generally avoid them in documentation, but if there's something specific you need covering relating to installation, we should add it somewhere for sure.

**Comment by collinbachi** [comment]
To test:
Navigate to the route attached to the frontend and create the admin user. 

This is basically step 12 in the confluence guide.

**Comment by collinbachi** [comment]
Correction: if they see the installation page, they are installed correctly. They do not actually have to proceed thru it.

**Comment by StarfallProjects** [comment]
@brianmrock think testing is covered by point 12 (already in there) Lemme know re.  FAQ

**Review by brianmrock — APPROVED** [review]

**Pull request merged**
